from enum import StrEnum


class RootCauseCategory(StrEnum):
    DEMAND_SPIKE = "DEMAND_SPIKE"
    STAFFING_SHORTFALL = "STAFFING_SHORTFALL"
    HANDLE_TIME_INCREASE = "HANDLE_TIME_INCREASE"
    ROUTING_CHANGE = "ROUTING_CHANGE"
    QUEUE_IMBALANCE = "QUEUE_IMBALANCE"
    ADHERENCE_DROP = "ADHERENCE_DROP"
    TRAINING_CAPACITY_LOSS = "TRAINING_CAPACITY_LOSS"
    PLATFORM_INCIDENT = "PLATFORM_INCIDENT"
    FORECAST_ERROR = "FORECAST_ERROR"
    DATA_QUALITY = "DATA_QUALITY"
    MULTIFACTOR = "MULTIFACTOR"
    NO_MATERIAL_INCIDENT = "NO_MATERIAL_INCIDENT"


class InvestigationStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    LIKELY = "LIKELY"
    INCONCLUSIVE = "INCONCLUSIVE"
